services:
  backend:
    image: melkoto/kittygram_backend:latest
    restart: always
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - postgres

  frontend:
    image: melkoto/kittygram_frontend:latest
    restart: always
    volumes:
      - static:/frontend_static

  gateway:
    image: melkoto/kittygram_gateway:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
      - frontend
      - postgres

  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  static:
  media:
  pg_data:
  frontend_static:
