volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: melkoto/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media_static

  frontend:
    env_file: .env
    image: melkoto/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/backend_static/collected_static
      - frontend:/app/static
  gateway:
    image: melkoto/kittygram_gateway:latest
    depends_on:
      - backend
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media_static
    ports:
      - "80:80"
