version: '3.9'

services:
  backend:
    image: melkoto/kittygram_backend:latest
    build: ./backend
    restart: always
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: melkoto/kittygram_frontend:latest
    build: ./frontend
    restart: always
    volumes:
      - frontend_static:/frontend/static
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'

  gateway:
    image: melkoto/kittygram_gateway:latest
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'

  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

volumes:
  static:
  media:
  pg_data:
  frontend_static:
