volumes:
  pg_data:    # Для базы данных
  static:     # Для статики
  media:      # Для медиафайлов
  frontend:   # Для фронтенда

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: melkoto/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media_static

  frontend:
    env_file: .env
    image: melkoto/kittygram_frontend:latest
    volumes:
      - static:/app/build

  gateway:
    image: melkoto/kittygram_gateway:latest
    depends_on:
      - backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media_static
    ports:
      - "80:80"
