services:
  backend:
    image: melkoto/kittygram_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres

  frontend:
    image: melkoto/kittygram_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/frontend/static

  gateway:
    image: melkoto/kittygram_gateway:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
      - postgres

  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  static:
  media:
  pg_data:
  frontend_static:
