package_update: true
package_upgrade: true
runcmd:
  - apt-get update -o Acquire::ForceIPv4=true
  - apt-get install -y -o Acquire::ForceIPv4=true docker.io docker-compose
  - systemctl enable docker
  - systemctl start docker
